### ISSUE TITLE
Update requirements definition with new requirements

### ISSUE THREAD

**Issue by brettnielsen** [brettnielsen/CS3450-tool-coop#59]
"I sent your projects out to the Tool Co-op for their feedback.  They were mostly pleased, but there are some things missing, and we've worked with them on the following additional requirements:

1. A slideshow / carousel on the main page that changes every few seconds
2. A modal that alerts the user that their submission has been accepted,
3. A tool-shed logo that appears twice on every page (both header and foot)
4. A contact us page that has a google map and a form to email questions
5. A project page that has pictures and descriptions of people using our tools for home remodel 
 
These subpages should have a teaser on the main page and link to the subpage. Teams are responsible for creating the actual written content of these pages (but the items can be made up). All pages should be designed to be visually appealing, content driven, with verbose descriptions.
 
**These requirements should be added to your requirements definition in BOLD, and should be broken down into manageable subtasks and added to your product backlog.**
 "

**Comment by ellisza** [comment]
Finished last sprint
